import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { palette } from "../theme-palette.mjs";

const rootDir = path.dirname(fileURLToPath(new URL("../package.json", import.meta.url)));
const sourceDir = path.join(rootDir, "src");
const paletteCssPath = path.join(rootDir, "palette.css");

const assets = [
  {
    kind: "css",
    source: path.join(sourceDir, "danwave.source.css"),
    output: path.join(rootDir, "danwave.css")
  },
  {
    kind: "css",
    source: path.join(sourceDir, "danwave-transitions.source.css"),
    output: path.join(rootDir, "danwave-transitions.css")
  },
  {
    kind: "theme",
    source: path.join(sourceDir, "danwave.source.json"),
    output: path.join(rootDir, "themes", "danwave.json")
  }
];

const AUTO_HEADER = "/* Auto-generated by scripts/build-theme.mjs. Edit the src/*.source.* files or theme-palette.mjs instead. */";

await fs.mkdir(sourceDir, { recursive: true });

for (const asset of assets) {
  await bootstrapSource(asset);
}

await writePaletteCss();

for (const asset of assets) {
  if (asset.kind === "css") {
    await buildCss(asset.source, asset.output);
    continue;
  }

  await buildTheme(asset.source, asset.output);
}

console.log("Palette build complete.");

async function bootstrapSource(asset) {
  if (await exists(asset.source)) {
    return;
  }

  const currentOutput = await fs.readFile(asset.output, "utf8");
  await fs.writeFile(asset.source, currentOutput, "utf8");
  console.log(`Bootstrapped ${path.relative(rootDir, asset.source)} from ${path.relative(rootDir, asset.output)}`);
}

async function writePaletteCss() {
  await fs.writeFile(paletteCssPath, `${buildPaletteRootBlock(AUTO_HEADER)}\n`, "utf8");
}

async function buildCss(sourcePath, outputPath) {
  const source = await fs.readFile(sourcePath, "utf8");
  const normalizedSource = stripGeneratedCssArtifacts(source);
  assertNoRawCssColors(normalizedSource, sourcePath);
  const output = `${buildPaletteRootBlock(AUTO_HEADER)}\n\n${normalizedSource.trimStart()}\n`;
  await fs.writeFile(outputPath, output, "utf8");
}

async function buildTheme(sourcePath, outputPath) {
  const source = await fs.readFile(sourcePath, "utf8");
  const theme = JSON.parse(source);
  assertNoRawThemeColors(theme, sourcePath);
  const builtTheme = replaceThemeValues(theme);
  const json = `${JSON.stringify(builtTheme, null, 2)}\n`;
  await fs.writeFile(outputPath, json, "utf8");
}

function replaceThemeValues(value) {
  if (Array.isArray(value)) {
    return value.map(replaceThemeValues);
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, nestedValue]) => [key, replaceThemeValues(nestedValue)])
    );
  }

  if (typeof value === "string") {
    const paletteToken = resolvePaletteToken(value);
    if (paletteToken) {
      return paletteToken;
    }
  }

  return value;
}

function stripGeneratedCssArtifacts(input) {
  return input
    .replace(/^\/\* Auto-generated by scripts\/build-theme\.mjs\.[^\n]*\*\/\s*/u, "")
    .replace(/^@import "\.\/palette\.css";\s*/u, "")
    .replace(/^:root\s*\{[\s\S]*?\}\s*/u, "");
}

function toKebabCase(value) {
  return value.replace(/[A-Z]/g, (character) => `-${character.toLowerCase()}`);
}

function resolvePaletteToken(value) {
  if (!value.startsWith("$palette.")) {
    return null;
  }

  const paletteKey = value.slice("$palette.".length);
  if (!(paletteKey in palette)) {
    throw new Error(`Unknown palette token $palette.${paletteKey}`);
  }

  return palette[paletteKey];
}

function assertNoRawCssColors(source, sourcePath) {
  const rawColorPattern = /#[0-9a-fA-F]{3,8}\b|rgba?\(|hsla?\(|\b(?:yellow|turquoise|transparent)\b/iu;
  const match = source.match(rawColorPattern);
  if (!match) {
    return;
  }

  throw new Error(`Raw CSS color literal \"${match[0]}\" found in ${path.relative(rootDir, sourcePath)}. Use palette variables instead.`);
}

function assertNoRawThemeColors(value, sourcePath, objectPath = "$") {
  if (Array.isArray(value)) {
    value.forEach((entry, index) => assertNoRawThemeColors(entry, sourcePath, `${objectPath}[${index}]`));
    return;
  }

  if (value && typeof value === "object") {
    for (const [key, nestedValue] of Object.entries(value)) {
      assertNoRawThemeColors(nestedValue, sourcePath, `${objectPath}.${key}`);
    }

    return;
  }

  if (typeof value !== "string") {
    return;
  }

  if (value.startsWith("$palette.")) {
    return;
  }

  const rawColorPattern = /^#[0-9a-fA-F]{3,8}$|^rgba?\(|^hsla?\(|^(?:yellow|turquoise|transparent)$/iu;
  if (!rawColorPattern.test(value.trim())) {
    return;
  }

  throw new Error(`Raw theme color literal \"${value}\" found in ${path.relative(rootDir, sourcePath)} at ${objectPath}. Use $palette.<token> instead.`);
}

function buildPaletteRootBlock(header) {
  const lines = [header, ":root {"];

  for (const [name, value] of Object.entries(palette)) {
    lines.push(`  --${toKebabCase(name)}: ${value};`);
  }

  lines.push("}");
  return lines.join("\n");
}

async function exists(targetPath) {
  try {
    await fs.access(targetPath);
    return true;
  } catch {
    return false;
  }
}