import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { cssAliases, palette, themeAliases } from "../theme-palette.mjs";

const rootDir = path.dirname(fileURLToPath(new URL("../package.json", import.meta.url)));
const sourceDir = path.join(rootDir, "src");
const paletteCssPath = path.join(rootDir, "palette.css");

const assets = [
  {
    kind: "css",
    source: path.join(sourceDir, "danwave.source.css"),
    output: path.join(rootDir, "danwave.css")
  },
  {
    kind: "css",
    source: path.join(sourceDir, "danwave-transitions.source.css"),
    output: path.join(rootDir, "danwave-transitions.css")
  },
  {
    kind: "theme",
    source: path.join(sourceDir, "danwave.source.json"),
    output: path.join(rootDir, "themes", "danwave.json")
  }
];

const AUTO_HEADER = "/* Auto-generated by scripts/build-theme.mjs. Edit the src/*.source.* files or theme-palette.mjs instead. */";

await fs.mkdir(sourceDir, { recursive: true });

for (const asset of assets) {
  await bootstrapSource(asset);
}

await writePaletteCss();

for (const asset of assets) {
  if (asset.kind === "css") {
    await buildCss(asset.source, asset.output);
    continue;
  }

  await buildTheme(asset.source, asset.output);
}

console.log("Palette build complete.");

async function bootstrapSource(asset) {
  if (await exists(asset.source)) {
    return;
  }

  const currentOutput = await fs.readFile(asset.output, "utf8");
  await fs.writeFile(asset.source, currentOutput, "utf8");
  console.log(`Bootstrapped ${path.relative(rootDir, asset.source)} from ${path.relative(rootDir, asset.output)}`);
}

async function writePaletteCss() {
  const lines = [AUTO_HEADER, ":root {"];

  for (const [name, value] of Object.entries(palette)) {
    lines.push(`  --${toKebabCase(name)}: ${value};`);
  }

  lines.push("}", "");
  await fs.writeFile(paletteCssPath, `${lines.join("\n")}`, "utf8");
}

async function buildCss(sourcePath, outputPath) {
  const source = await fs.readFile(sourcePath, "utf8");
  const normalizedSource = stripGeneratedCssArtifacts(source);
  const replaced = replaceFromAliasMap(normalizedSource, cssAliases, true);
  const output = `${AUTO_HEADER}\n@import \"./palette.css\";\n\n${replaced.trimStart()}\n`;
  await fs.writeFile(outputPath, output, "utf8");
}

async function buildTheme(sourcePath, outputPath) {
  const source = await fs.readFile(sourcePath, "utf8");
  const theme = JSON.parse(source);
  const builtTheme = replaceThemeValues(theme);
  const json = `${JSON.stringify(builtTheme, null, 2)}\n`;
  await fs.writeFile(outputPath, json, "utf8");
}

function replaceThemeValues(value) {
  if (Array.isArray(value)) {
    return value.map(replaceThemeValues);
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, nestedValue]) => [key, replaceThemeValues(nestedValue)])
    );
  }

  if (typeof value === "string") {
    const paletteToken = resolvePaletteToken(value);
    if (paletteToken) {
      return paletteToken;
    }

    const paletteKey = themeAliases[value];
    if (paletteKey) {
      return palette[paletteKey];
    }
  }

  return value;
}

function replaceFromAliasMap(input, aliases, useCssVars) {
  return Object.entries(aliases)
    .sort((left, right) => right[0].length - left[0].length)
    .reduce((text, [seed, paletteKey]) => {
      const replacement = useCssVars ? `var(--${toKebabCase(paletteKey)})` : palette[paletteKey];
      if (seed.startsWith("#")) {
        const escapedSeed = escapeRegExp(seed);
        return text.replace(new RegExp(`${escapedSeed}(?![0-9a-fA-F])`, "g"), replacement);
      }

      return text.replaceAll(seed, replacement);
    }, input);
}

function stripGeneratedCssArtifacts(input) {
  return input
    .replace(/^\/\* Auto-generated by scripts\/build-theme\.mjs\.[^\n]*\*\/\s*/u, "")
    .replace(/^@import "\.\/palette\.css";\s*/u, "");
}

function toKebabCase(value) {
  return value.replace(/[A-Z]/g, (character) => `-${character.toLowerCase()}`);
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function resolvePaletteToken(value) {
  if (!value.startsWith("$palette.")) {
    return null;
  }

  const paletteKey = value.slice("$palette.".length);
  return palette[paletteKey] ?? null;
}

async function exists(targetPath) {
  try {
    await fs.access(targetPath);
    return true;
  } catch {
    return false;
  }
}